name: Continuous Delivery on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Container platform
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Shutdown active containers
      run: docker-compose down --remove-orphans || true

    - name: Build and start Docker platform
      run: docker-compose up --build -d
